import { Rack } from "@/types/RacksTypes";

export const fakeRack: Rack = {
    columns: 4,
    rows: 3,
    rackName: "Démonstration",
    idrack: "314",
    bottles: [
        {
            "id": "jfdjdhddfvbyt",
            "nom": "Château Margaux",
            "millesime": 2015,
            "appellation": "Margaux AOC",
            "exploitation": "Château Margaux",
            "cepage": "Cabernet Sauvignon",
            "pays": "France",
            "type": "vin",
            "couleur": "rouge",
            "saveur": null,
            "corps": "plein",
            "potentiel": "moyen",
            "status": "A boire",
            "degre": 13.5,
            "accords": "agneau",
            "prix": 600,
            "achat": "2022-02-17",
            "drink": null,
            "rackId": "314",
            "index": 0
        },
        {
            "id": "jfdjdhdhjj",
            "nom": "Château Margaux",
            "millesime": 2015,
            "appellation": "Margaux AOC",
            "exploitation": "Château Margaux",
            "cepage": "Cabernet Sauvignon",
            "pays": "France",
            "type": "vin",
            "couleur": "rouge",
            "saveur": null,
            "corps": "plein",
            "potentiel": "moyen",
            "status": "A boire",
            "degre": 13.5,
            "accords": "agneau",
            "prix": 600,
            "achat": "2022-02-17",
            "drink": null,
            "rackId": "314",
            "index": 1
        },
        {
            "id": "latqudbncghc",
            "nom": "Napa Valley",
            "millesime": 2019,
            "appellation": "Napa Valley AVA",
            "exploitation": "Opus One Winery",
            "cepage": "Cabernet Sauvignon",
            "pays": "États-Unis",
            "type": "vin",
            "couleur": "rouge",
            "saveur": null,
            "corps": "plein",
            "potentiel": "long",
            "status": "A garder",
            "degre": 14.5,
            "accords": "Filet mignon",
            "prix": 450,
            "achat": "2021-09-19",
            "drink": null,
            "rackId": "314",
            "index": 2
        },
        {
            "id": "kjhyrtey",
            "nom": "Bolgheri",
            "millesime": 2018,
            "appellation": "Bolgheri Sassicaia DOC",
            "exploitation": "Tenuta San Guido",
            "cepage": "Cabernet Sauvignon",
            "pays": "Italie",
            "type": "vin",
            "couleur": "rouge",
            "saveur": null,
            "corps": "plein",
            "potentiel": "moyen",
            "status": "A boire",
            "degre": 14.5,
            "accords": "Osso buco",
            "prix": 250,
            "achat": "2021-09-19",
            "drink": null,
            "rackId": "314",
            "index": 3
        },
        {
            "id": "qwerty",
            "nom": "Bolgheri",
            "millesime": 2018,
            "appellation": "Bolgheri Sassicaia DOC",
            "exploitation": "Tenuta San Guido",
            "cepage": "Cabernet Sauvignon",
            "pays": "Italie",
            "type": "vin",
            "couleur": "rouge",
            "saveur": null,
            "corps": "plein",
            "potentiel": "moyen",
            "status": "A boire",
            "degre": 14.5,
            "accords": "Osso buco",
            "prix": 250,
            "achat": "2021-09-19",
            "drink": null,
            "rackId": "314",
            "index": 4
        },
        {
            "id": "poiuyter",
            "nom": "Chablis Grand Cru AOC",
            "millesime": 2019,
            "appellation": "Chablis",
            "exploitation": "Domaine William Fèvre",
            "cepage": "Chardonnay",
            "pays": "France",
            "type": "vin",
            "couleur": "blanc",
            "saveur": "sec",
            "corps": "moyen",
            "potentiel": "moyen",
            "status": "A boire",
            "degre": 13,
            "accords": "huitres",
            "prix": 80,
            "achat": "2021-06-21",
            "drink": null,
            "rackId": "314",
            "index": 5,
        },
        {
            "id": "poiuytererre",
            "nom": "Chablis Grand Cru AOC",
            "millesime": 2019,
            "appellation": "Chablis",
            "exploitation": "Domaine William Fèvre",
            "cepage": "Chardonnay",
            "pays": "France",
            "type": "vin",
            "couleur": "blanc",
            "saveur": "sec",
            "corps": "moyen",
            "potentiel": "moyen",
            "status": "A boire",
            "degre": 13,
            "accords": "huitres",
            "prix": 80,
            "achat": "2021-06-21",
            "drink": null,
            "rackId": "314",
            "index": 6,
        },
        {
            "id": "poiuytereze",
            "nom": "Chablis Grand Cru AOC",
            "millesime": 2019,
            "appellation": "Chablis",
            "exploitation": "Domaine William Fèvre",
            "cepage": "Chardonnay",
            "pays": "France",
            "type": "vin",
            "couleur": "blanc",
            "saveur": "sec",
            "corps": "moyen",
            "potentiel": "moyen",
            "status": "A boire",
            "degre": 13,
            "accords": "huitres",
            "prix": 80,
            "achat": "2021-06-21",
            "drink": null,
            "rackId": "314",
            "index": 7,
        },
        {
            "id": "hjetbvxf",
            "nom": "Whispering Angel 2023",
            "millesime": 2023,
            "appellation": "Côtes de Provence AOC",
            "exploitation": "Château d'Esclans",
            "cepage": "Grenache",
            "pays": "France",
            "type": "vin",
            "couleur": "rose",
            "saveur": "fruite",
            "corps": "moyen",
            "potentiel": "court",
            "status": "A boire",
            "degre": 13,
            "accords": "sushi",
            "prix": 37.75,
            "achat": "2024-06-02",
            "drink": null,
            "rackId": "314",
            "index": 8,
        },
        {
            "id": "qazwsxedc",
            "nom": "",
            "millesime": null,
            "appellation": "",
            "exploitation": null,
            "cepage": null,
            "pays": null,
            "type": "vide",
            "couleur": null,
            "saveur": null,
            "corps": null,
            "potentiel": null,
            "status": null,
            "degre": null,
            "accords": null,
            "prix": 37.75,
            "achat": null,
            "drink": null,
            "rackId": "314",
            "index": 9,
        },
        {
            "id": "rfvtgb",
            "nom": "Moët & Chandon Brut Impérial",
            "millesime": 2023,
            "appellation": "Champagne AOC",
            "exploitation": "Moët & Chandon",
            "cepage": "Pinot Noir, Pinot Meunier, Chardonnay",
            "pays": "France",
            "type": "champagne",
            "couleur": null,
            "saveur": "fruite",
            "corps": "moyen",
            "potentiel": "court",
            "status": "A boire",
            "degre": 12,
            "accords": "huitres",
            "prix": 40,
            "achat": "2024-06-02",
            "drink": null,
            "rackId": "314",
            "index": 10,
        },
        {
            "id": "yhnujmtt",
            "nom": "Moët & Chandon Brut Impérial",
            "millesime": 2023,
            "appellation": "Champagne AOC",
            "exploitation": "Moët & Chandon",
            "cepage": "Pinot Noir, Pinot Meunier, Chardonnay",
            "pays": "France",
            "type": "champagne",
            "couleur": null,
            "saveur": "fruite",
            "corps": "moyen",
            "potentiel": "court",
            "status": "A boire",
            "degre": 12,
            "accords": "sushi",
            "prix": 40,
            "achat": "2024-06-02",
            "drink": null,
            "rackId": "314",
            "index": 12,
        }
    ]
}
