import { Rack } from "@/types/RacksTypes";

export const fakeRack: Rack = {
    columns: 4,
    rows: 3,
    rackName: "Démonstration",
    idrack: "314",
    bottles: [
        {
            "accords": [],
            "achat": "01-01-2022",
            "appellation": "Bordeaux",
            "couleur": "rouge",
            "cuvee": "Prestige",
            "exploitation": "Chateau Lapompe",
            "gout": "",
            "id": "jfdjdhdhjj",
            "index": 0,
            "millesime": 2019,
            "pays": "France",
            "prix": 8,
            "rackId": "314",
            "type": "vin",
            "drink": null
        },
        {
            "accords": [],
            "achat": "01-01-2022",
            "appellation": "Bordeaux",
            "couleur": "rouge",
            "cuvee": "",
            "exploitation": "Chateau Lapompe",
            "gout": "",
            "id": "hdjskwud",
            "index": 1,
            "millesime": 2019,
            "pays": "France",
            "prix": 9,
            "rackId": "314",
            "type": "vin",
            "drink": null
        },
        {
            "accords": [],
            "achat": "01-01-2022",
            "appellation": "Bourgogne",
            "couleur": "rouge",
            "cuvee": "Speciale",
            "exploitation": "Chateau Margot",
            "gout": "",
            "id": "latqudbncghc",
            "index": 2,
            "millesime": 2019,
            "pays": "France",
            "prix": 7,
            "rackId": "314",
            "type": "vin",
            "drink": null
        },
        {
            "accords": [],
            "achat": "01-01-2022",
            "appellation": "Bourgogne",
            "couleur": "blanc",
            "cuvee": "",
            "exploitation": "Chateau Margot",
            "gout": "sec",
            "id": "kjhyrtey",
            "index": 3,
            "millesime": 2020,
            "pays": "France",
            "prix": 11,
            "rackId": "314",
            "type": "vin",
            "drink": null
        },
        {
            "accords": [],
            "achat": "01-01-2022",
            "appellation": "Bourgogne",
            "couleur": "blanc",
            "cuvee": "",
            "exploitation": "Chateau Laffond",
            "gout": "",
            "id": "qwerty",
            "index": 4,
            "millesime": 2015,
            "pays": "France",
            "prix": 8,
            "rackId": "314",
            "type": "vin",
            "drink": null
        },
        {
            "accords": [],
            "achat": "01-01-2022",
            "appellation": "Champagne",
            "couleur": "pétillant",
            "cuvee": "An 2000",
            "exploitation": "Chateau Margot",
            "gout": "demi-sec",
            "id": "poiuyter",
            "index": 5,
            "millesime": 2000,
            "pays": "France",
            "prix": 50,
            "rackId": "314",
            "type": "champagne",
            "drink": null
        },
        {
            "accords": [],
            "achat": "01-01-2022",
            "appellation": "Chouffe",
            "couleur": "blonde",
            "cuvee": "",
            "exploitation": "",
            "gout": "",
            "id": "poiuytererre",
            "index": 6,
            "millesime": 2024,
            "pays": "Belgique",
            "prix": 5,
            "rackId": "314",
            "type": "biere",
            "drink": null
        },
        {
            "accords": [],
            "achat": "01-01-2022",
            "appellation": "",
            "couleur": "",
            "cuvee": "",
            "exploitation": "",
            "gout": "",
            "id": "poiuytereze",
            "index": 7,
            "millesime": 0,
            "pays": "",
            "prix": 0,
            "rackId": "314",
            "type": "vide",
            "drink": null
        },
        {
            "accords": [],
            "achat": "01-01-2022",
            "appellation": "Champagne",
            "couleur": "rouge",
            "cuvee": "",
            "exploitation": "Chateau Reims",
            "gout": "",
            "id": "hjetbvxf",
            "index": 8,
            "millesime": 2019,
            "pays": "France",
            "prix": 28,
            "rackId": "314",
            "type": "champagne",
            "drink": null
        },
        {
            "accords": [],
            "achat": "01-01-2022",
            "appellation": "Bourgogne",
            "couleur": "rose",
            "cuvee": "",
            "exploitation": "Chateau Piquette",
            "gout": "",
            "id": "qazwsxedc",
            "index": 9,
            "millesime": 2019,
            "pays": "France",
            "prix": 38,
            "rackId": "314",
            "type": "vin",
            "drink": null
        },
        {
            "accords": [],
            "achat": "",
            "appellation": "",
            "couleur": "",
            "cuvee": "",
            "exploitation": "",
            "gout": "",
            "id": "rfvtgb",
            "index": 10,
            "millesime": 0,
            "pays": "",
            "prix": 0,
            "rackId": "314",
            "type": "vide",
            "drink": null
        },
        {
            "accords": [],
            "achat": "",
            "appellation": "",
            "couleur": "",
            "cuvee": "",
            "exploitation": "",
            "gout": "",
            "id": "yhnujmtt",
            "index": 11,
            "millesime": 0,
            "pays": "",
            "prix": 0,
            "rackId": "314",
            "type": "vide",
            "drink": null
        }
    ]
}
